POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Son To",
    "dateOfBirth": "1992-10-01",
    "ssn": "011092-295Y",
    "gender": "male",
    "occupation": "Programmer"
}