POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Son To",
    "dateOfBirth": "01/10/1992",
    "ssn": "0213832-123Y",
    "gender": "male",
    "occupation": "Terminator"
}